import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CircleButton from "@/pages/CircleButton";










export default function Home() {



  return (
<>
      <Head>
          <title>Bootcamp</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/bootcamp-2025.03-logo.jpg" />
      </Head>

      <div
          style={{
              minHeight: '100vh',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
          }}
      >
          <CircleButton
              onClick={()=>console.log("Welcome please sign in")}
              size={500}
              bgColor="#007bff"
              hoverColor="#0056b3"

          >

          </CircleButton>

      </div>
</>
  );


}
