

import Head from "next/head";
import {useEffect, useState} from "react";
import axios from "axios";



export default function ChatGuestPage() {


    const [myMessage ,setMyMessage]=useState("");


    function handleMyMessage(event){
        console.log(" I Write this:"+ event.target.value);
        setMyMessage(event.target.value);




    }



    async function  sendMyMessage(e){
        e.preventDefault();
        console.log("Hi from sendMyMessage function");

        try{

            const response = await axios.post()

        }
        catch (err){
            console.log(err+" THIS IS THE ERROR");
        }




    }





    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="page-container">
                <header>
                    <div className="header-content">
                        <div className="header-brand">
                            <img src="./bootcamp-2025.03-logo.jpg" alt="Logo" className="header-logo"/>
                            <div className="header-title">Chat Application</div>
                        </div>

                    </div>
                </header>
                <div className="center-container">



                    <main className="main-container">
                        <div className="chat-window">

                            <div className="chat-model-select">
                                <select id="model-select">
                                    <option value="gpt-3.5-turbo">GPT-3.5 Turbo</option>
                                    <option value="gpt-4">GPT-4</option>
                                    <option value="gpt-4-turbo">GPT-4 Turbo</option>
                                    <option value="custom-model">Custom Model...</option>
                                </select>
                            </div>


                            <div className="messages">
                                <div className="message bot">Hello! I’m ChatGPT—how can I help you today?</div>
                                <div className="message user" value={myMessage}></div>
                            </div>


                            {/* forma gia thn apostolh munhmatos pros to llama */}
                            <form onSubmit={sendMyMessage}>
                            <div className="input-container">
                                <input type="text"    value={myMessage}
                                       onChange={handleMyMessage} placeholder="Type a message…"/>
                                <button>  ➤</button>
                            </div>
                        </form>
                            {/* TELOS forma gia thn apostolh munhmatos pros to llama */}
                        </div>
                    </main>
                </div>
                <footer>© 2025 Chat App, Inc.</footer>
            </div>
        </>
    );
}
